name: juvuit_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.1.2
  dio: ^5.7.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  flutter_card_swiper: ^7.0.2
  card_swiper: ^3.0.1
  intl: ^0.20.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  http: ^0.13.6
  apple_maps_flutter: ^1.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/homescreen/
