#!/bin/bash

echo "🍎 Verificación de Configuración Apple Developer"
echo "================================================"

echo ""
echo "📱 Información del Proyecto:"
echo "Bundle ID: com.example.juvuitFlutter"
echo "Team ID: UZG9XMXAMN"
echo "App Name: Juvuit Flutter"

echo ""
echo "🔧 Pasos para completar la configuración:"
echo ""
echo "1. Ve a https://developer.apple.com/account/"
echo "2. Inicia sesión con tu cuenta de Apple Developer"
echo "3. Ve a 'Certificates, Identifiers & Profiles'"
echo "4. En 'Identifiers', busca o crea el App ID: com.example.juvuitFlutter"
echo "5. Habilita 'Sign In with Apple' en las capabilities"
echo ""
echo "6. Crea un Service ID:"
echo "   - Description: Juvuit Flutter Sign In Service"
echo "   - Identifier: com.example.juvuitFlutter.signin"
echo "   - Habilita 'Sign In with Apple'"
echo "   - Configura el Primary App ID como: com.example.juvuitFlutter"
echo ""
echo "7. En Firebase Console:"
echo "   - Ve a Authentication > Sign-in method"
echo "   - Habilita Apple como proveedor"
echo "   - Service ID: com.example.juvuitFlutter.signin"
echo "   - Apple Team ID: UZG9XMXAMN"
echo ""
echo "✅ Tu proyecto ya tiene:"
echo "   - Development Team configurado"
echo "   - Bundle ID configurado"
echo "   - Entitlements actualizados con Sign In with Apple"
echo ""
echo "❌ Falta configurar en Apple Developer Console y Firebase"
