// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATBhEy7uvuMRwA1kGJHkcxtd0C3yMrZ4w',
    appId: '1:852726617261:android:2eb543bf73d9714168e224',
    messagingSenderId: '852726617261',
    projectId: 'juvuit-flutter',
    storageBucket: 'juvuit-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFV21b19QaUO5mjI8Xma-cNHfRkUWPqYA',
    appId: '1:852726617261:ios:131fcc6be2c780ad68e224',
    messagingSenderId: '852726617261',
    projectId: 'juvuit-flutter',
    storageBucket: 'juvuit-flutter.firebasestorage.app',
    androidClientId: '852726617261-67rvaa4fs4af3vjr2pc0916p0ul4c57k.apps.googleusercontent.com',
    iosClientId: '852726617261-3ruqqs4hotn7846cp6t322a5ahq6ciif.apps.googleusercontent.com',
    iosBundleId: 'com.witu.app',
  );

}